### ISSUE TITLE
need node version check or compatibility

### ISSUE THREAD

**Issue by pieper** [commontk/CTK-web#5]
After checking out the repository and running 'npm install' (no errors) I ran 'npm run build' and got the error pasted below.  This machine has node v0.10.23 which I suspect is the issue.  We should check version or provide a polyfill.
#14 ctk-web (master=)$ npm run build

> commontk-web@0.0.1 build /Users/pieper/ctk/ctk-web
> webpack --progress --colors

```
Hash: 021ae673f4179ada77ec  
Version: webpack 1.13.1
Time: 9332ms
 Asset    Size  Chunks             Chunk Names
ctk.js  154 kB       0  [emitted]  main
    + 43 hidden modules

ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[name]_[local]_[hash:base64:5]!./~/postcss-loader!./lib/style/TransferFunctionEditor.mcss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/pieper/ctk/ctk-web/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/Users/pieper/ctk/ctk-web/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (/Users/pieper/ctk/ctk-web/node_modules/postcss-loader/index.js:63:10)
 @ ./lib/style/TransferFunctionEditor.mcss 4:14-212
```

**Comment by jcfr** [comment]
As a side note, Look like you are using a very old version ... from 2013

See https://nodejs.org/en/download/releases/

**Comment by pieper** [comment]
Yes, updating node worked for me, but a version check would still be wise.

**Comment by jcfr** [comment]
This could be done adding a line to `package.json`. See https://docs.npmjs.com/files/package.json#engines

We could then specify minimum required version of node to be v4.2.6 .. the default one used on circleci.

See https://circleci.com/docs/build-image-trusty/#nodejs

Cc: @zachmullen

**Comment by zachmullen** [comment]
We have an engine identifier in our package.json already actually, feel free to bump those requirements to whatever version is needed.
